# !/usr/bin/env python
# -*- coding: utf-8 -*-

 #### urls is used by web.py. When a GET request is received, the corresponding class is executed.
urls = [
#    '/',  'webpages.home',
#    '/home',  'webpages.home',
#    '/cv', 'webpages.change_values',
#    '/vo', 'webpages.view_options',
#    '/co', 'webpages.change_options',
#    '/vs', 'webpages.view_stations',
#    '/cs', 'webpages.change_stations',
##    '/csb', 'webpages.change_station_board',
#    '/csm', 'webpages.change_station_main',
#    '/ars', 'webpages.add_radio_station',
#    '/sn', 'webpages.get_set_station',
#    '/vr', 'webpages.view_runonce',
#    '/cr', 'webpages.change_runonce',
#    '/vp', 'webpages.view_programs',
#    '/mp', 'webpages.modify_program',
#    '/cp', 'webpages.change_program',
#    '/dp', 'webpages.delete_program',
#    '/ep', 'webpages.enable_program',
#    '/vl', 'webpages.view_log',
#    '/cl', 'webpages.clear_log',
#    '/tl', 'webpages.truncate_log',
#    '/lo', 'webpages.log_options',
#    '/rp', 'webpages.run_now',
#    '/ttu', 'webpages.toggle_temp',
#    '/rev', 'webpages.show_revision',
#    '/el', 'webpages.email_log',
#    '/wl', 'webpages.water_log',
#    '/rc', 'webpages.restore_configuration',
#    '/sc', 'webpages.save_configuration',
#    '/ping', 'webpages.ping',
#    '/debuglog', 'webpages.debug_log',
#    '/api/status', 'webpages.api_status',
#    '/api/log', 'webpages.api_log',
#    '/login', 'webpages.login',
#    '/logout', 'webpages.logout',
#    '/restart', 'webpages.sw_restart',
#    '/reboot_all', 'webpages.reboot_all',
#    '/shutdown_all', 'webpages.shutdown_all',
#    '/unreachable', 'webpages.sw_unreachable',
    '/',  'webpages.view_log',
    '/vo', 'webpages.view_options',
    '/co', 'webpages.change_options',
    '/vl', 'webpages.view_log',
    '/cl', 'webpages.clear_log',
    '/wl', 'webpages.water_log',
    '/login',  'webpages.login',
    '/logout',  'webpages.logout',
]
